name: cat_dog_classifier_hosted
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  http: ^1.2.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  html: ^0.15.4

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
